### ISSUE TITLE
[OIDC] discovery_url rejected by SSRF guard: host 'idp_hostname' resolves to private/loopback 10.10.10.10

### ISSUE THREAD

**Issue by SeeJayEmm** [PegaProx/project-pegaprox#412]
## Describe the bug
As of 0.9.10.1 OIDC no longer works due to SSRF hardening. I've searched the settings and the documentation and I cannot find an option to add the IP to an allow-list or to bypass the SSRF guard for OIDC.

## Steps to Reproduce
1. Use an IdP that resolves to a private IP.

## Expected behavior
Ability to login with an IdP that is hosted internally.

## Environment
- **PegaProx Version:** 0.9.10.1
- **Installation Method:** Manual
- **OS:** Debian 13
- **Browser:** Firefox
- **Behind Reverse Proxy?** No
- **UI?** Modern

## Logs

```
May 13 16:51:10 pegaprox pegaprox[122629]: [ssrf-guard] rejected outbound URL: host 'idp-hostname' resolves to private/loopback 10.10.10.10 (len=61)
May 13 16:51:10 pegaprox pegaprox[122629]: [OIDC] discovery_url rejected by SSRF guard: host 'idp-hostname' resolves to private/loopback 10.10.10.10
May 13 16:51:10 pegaprox pegaprox[122629]: Exception on /api/settings/oidc/test [POST]
May 13 16:51:10 pegaprox pegaprox[122629]: Traceback (most recent call last):
May 13 16:51:10 pegaprox pegaprox[122629]:   File "/opt/PegaProx/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
May 13 16:51:10 pegaprox pegaprox[122629]:     response = self.full_dispatch_request()
May 13 16:51:10 pegaprox pegaprox[122629]:   File "/opt/PegaProx/venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
May 13 16:51:10 pegaprox pegaprox[122629]:     rv = self.handle_user_exception(e)
May 13 16:51:10 pegaprox pegaprox[122629]:   File "/opt/PegaProx/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
May 13 16:51:10 pegaprox pegaprox[122629]:     rv = self.dispatch_request()
May 13 16:51:10 pegaprox pegaprox[122629]:   File "/opt/PegaProx/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
May 13 16:51:10 pegaprox pegaprox[122629]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May 13 16:51:10 pegaprox pegaprox[122629]:            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
May 13 16:51:10 pegaprox pegaprox[122629]:   File "/opt/PegaProx/pegaprox/utils/auth.py", line 810, in decorated_function
May 13 16:51:10 pegaprox pegaprox[122629]:     return f(*args, **kwargs)
May 13 16:51:10 pegaprox pegaprox[122629]:   File "/opt/PegaProx/pegaprox/api/auth.py", line 306, in oidc_test_connection
May 13 16:51:10 pegaprox pegaprox[122629]:     if endpoints.get('_discovery_used'):
May 13 16:51:10 pegaprox pegaprox[122629]:        ^^^^^^^^^^^^^
May 13 16:51:10 pegaprox pegaprox[122629]: AttributeError: 'NoneType' object has no attribute 'get'
```

## Checklist
- [X] I have searched existing issues to make sure this is not a duplicate
- [X] I am using the latest version of PegaProx

**Comment by MrMasterbay** [comment]
@SeeJayEmm Litertally just pushed out a fix for that :).

Was not even our change flask-core and urllib closed that down -> created now a workaround.

**Comment by MrMasterbay** [comment]
@SeeJayEmm could you confirm if it's working in v0.9.10.2?

**Comment by robertjakub** [comment]
a workaround looks good. nonetheless... can you share how to access the IP whitelist for SSRF? unfortunately, introducing this feature broke my instance...  (IdP, SIEM resolves to internal /RFC1918 IPs)

**Comment by robertjakub** [comment]
for quick and dirty hack, I modified the allow_private: bool = False to True (utils/url_security.py)

**Comment by mkellermann97** [comment]
Hey @SeeJayEmm — two separate things in your trace:

1. The `AttributeError: 'NoneType' object has no attribute 'get'` at `api/auth.py:306` is a crash bug that's already fixed in 0.9.10.2 (came up via @gerwin221 on #188 too). Upgrading to 0.9.10.2 will get you a clean error response instead of the 500 traceback — you'll see the SSRF-guard rejection surfaced through the UI properly instead of a stack trace.

2. The actual underlying issue — that the SSRF guard refuses to talk to a private-IP IdP at all — is the real ask. We don't currently have a config knob to opt-out the OIDC discovery path specifically. The guard is intentionally aggressive because it covers user-supplied URLs in other code paths where the threat model is "attacker controls the URL"; for admin-set OIDC config the threat model is different, and a per-feature allowlist makes sense.

That config knob is on @MrMasterbay's plate — he owns the OIDC core and gets back from holiday on May 18, so the proper fix lands after he's back. No clean workaround in 0.9.10.1/.2 short of fronting the IdP behind a public-IP reverse proxy, unfortunately.

Donations at https://opencollective.com/pegaprox help us push this kind of OIDC infrastructure work up the list — completely optional, no pressure.

— Marcus

**Comment by mkellermann97** [comment]
Update — I picked this up this evening instead of parking it for Nico. Two parts:

1. **Crash trace at `api/auth.py:306`** — already fixed in v0.9.10.2 (came up via @gerwin221 on #188 too). Upgrading from 0.9.10.1 will replace the 500 traceback with a clean "Endpoint Resolution" error step in the UI.

2. **The actual private-IP allowlist for OIDC** — now landed on the `Testing` branch as commit `4e9ee53`. New opt-in setting `oidc_allow_private_ip` (default OFF, secure). When you turn it on, the SSRF guard for the OIDC discovery URL specifically lets through 10.x / 192.168.x / 172.16-31.x — but metadata IPs (169.254.169.254 etc.) stay blocked, and every other outbound path (webhooks, plugin upstreams, SAML metadata) keeps the strict guard.

Bonus: when the flag is off and the rejection happens, the error detail you see now includes a hint pointing you at the new setting, so the next person hitting this doesn't have to dig through tickets.

Workaround that should work right now if you can't wait for the next release-cut and you're on 0.9.10.2+ with this Testing build:

```bash
curl -X POST https://<your-host>:5000/api/settings/oidc \
  -H "Content-Type: application/json" \
  -b session=<your-admin-session> \
  -d '{"oidc_allow_private_ip": true}'
```

Then retry the OIDC test-connection. UI toggle for the new setting is a follow-up — the backend is the unblocking piece.

Verified end-to-end with 7 SSRF-guard unit cases + 6 in-PegaProx integration cases (default-off still rejects, opt-in accepts your shape of URL, metadata stays blocked, public-IP regression-free). Tip jar's https://opencollective.com/pegaprox if this unblocks you and you feel like throwing a coin at the kind of work that keeps the lights on.

— Marcus

**Comment by mkellermann97** [comment]
Quick follow-up — UI toggle now wired up too (commit `97f36a2`). New section in OIDC settings called "Internal IdP / Private Network" with a checkbox; mirrors the existing IdP-TLS-Verify pattern so it should feel familiar. Default OFF (secure), turn it on and the card flips yellow with a reminder that cloud-metadata IPs (169.254.x.x etc.) still stay blocked.

Translated to all 7 supported languages (DE / EN / FR / ES / PT / KO / IT) — 42 entries total. No more curl needed once this rolls into a release.

— Marcus

**Comment by robertjakub** [comment]
unfortunately, in 0.9.10.3: 

`
 [OIDC] Token exchange failed: Token endpoint failed pre-flight URL validation
`

the discovery is fixed, but we need to fix also the token and userinfo requests. Something like: 

```
--- utils/oidc.py.orig  2026-05-19 15:14:28.000000000 +0000
+++ utils/oidc.py       2026-05-21 06:04:35.520536315 +0000
@@ -295,9 +295,11 @@
     if code_verifier:
         data['code_verifier'] = code_verifier
     
+    allow_private_ip = bool(config.get('oidc_allow_private_ip', False)) 
+
     try:
         try:
-            sanitize_outbound_url(endpoints['token'])
+            sanitize_outbound_url(endpoints['token'], allow_private=allow_private_ip)
         except SsrfError as guard_err:
             logging.warning(f"[OIDC] token endpoint rejected by SSRF guard: {guard_err}")
             return {'error': 'Token endpoint failed pre-flight URL validation'}
@@ -408,6 +410,8 @@
     endpoints = get_oidc_endpoints(config)
     
     user_info = {}
+
+    allow_private_ip = bool(config.get('oidc_allow_private_ip', False))
     
     try:
         if config.get('provider') == 'entra' and endpoints.get('graph_me'):
@@ -430,7 +434,7 @@
         # Fallback or generic OIDC: use standard userinfo endpoint
         if not user_info and endpoints.get('userinfo'):
             try:
-                sanitize_outbound_url(endpoints['userinfo'])
+                sanitize_outbound_url(endpoints['userinfo'], allow_private=allow_private_ip)
             except SsrfError as guard_err:
                 logging.warning(f"[OIDC] userinfo endpoint rejected by SSRF guard: {guard_err}")
                 return {'error': 'Userinfo endpoint failed pre-flight URL validation'}
```

**Comment by SeeJayEmm** [comment]
Sorry I went radio silent after the report, notifications weren't working. I'm encountering the same error as robertjakub. I see the commit and will test once the next release is cut.

**Comment by mkellermann97** [comment]
@SeeJayEmm @robertjakub — v0.9.11 is out. `allow_private` now covers token + userinfo (`add318b`), not just discovery. That's what was tripping you on 0.9.10.3. Closing — reopen if anything else surfaces.

— Marcus
